root: true
env:
  node: true
extends:
  - 'plugin:prettier/recommended'
  - 'plugin:vue/vue3-essential'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - '@vue/prettier'
  - '@vue/prettier/@typescript-eslint'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2020